### ISSUE TITLE
Technical: fatal error: Array index out of range

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#32]
1.Try to add a new title under 'Rating for technical'
2. Without tabbing  out or clicking elsewhere, click on Add again.
3. App crashes.

**Comment by Tharani-p** [comment]
I have fixed the issue.

**Comment by srilatha-sriram** [comment]
App still crashes if you remove 'Enter Title' and click on 'Add' again.
Please  perform thorough unit testing before sending a fix for verification.

**Comment by Tharani-p** [comment]
I have fixed the issue and committed code.for me its working fine and still you are facing the same problem. let me know.

**Comment by rajeshnath3899** [comment]
crash still exists not able to reproduce always

**Comment by Tharani-p** [comment]
I will work on it.

**Comment by rajeshnath3899** [comment]
padalingam can you also look into this issue ..

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
