### ISSUE TITLE
Candidate Module : Search field crashing when searching for a candidate.

### ISSUE THREAD

**Issue by sudhanshu-saraswat** [vipin1006/eHire#33]

**Comment by PratibhaSawargi** [comment]
Okay, i will work on it.

**Comment by PratibhaSawargi** [comment]
I have fixed the SearchField issue.

**Comment by sudhanshu-saraswat** [comment]
Issue  still persist.Refer the screen shot
![screen shot 2016-01-28 at 10 05 04 am](https://cloud.githubusercontent.com/assets/16332003/12635194/bccec268-c5a6-11e5-8a85-e94bee4fb0d5.png)

**Comment by PratibhaSawargi** [comment]
I have fixed.Verify.

**Comment by sudhanshu-saraswat** [comment]
Closed
