### ISSUE TITLE
Validation of Name, Experience, Phone number ,Requisition fields not as expected

### ISSUE THREAD

**Issue by rajeshnath3899** [vipin1006/eHire#38]
When we provide invalid data and tab out its focus is moved  to next successive textfield once we click Ok button on the alert window 

Expected scenario : Once we tab out of a field if its invalid once alert is popped up and end user clicks on Ok button it has to retain the focus onto the current textfield instead of moving to the next successive field

Steps to reproduce : 

1) Launch the application 
2) Add a new technology
3) Add in the candidate details like person name give some invalid value say numbers 
4) Tab out you get an alert window 
5) Click on the Ok button of alert window 
6) The focus is on the Experience Text Field now

**Comment by rajeshnath3899** [comment]
Pratibha can you let me know the ETA for fixing this bug

**Comment by PratibhaSawargi** [comment]
Hi Rajesh,
I have fixed the issue,can you please check and let me know.

**Comment by rajeshnath3899** [comment]
issue still persists can you please check this again 
![screen shot 2016-01-27 at 6 59 03 pm](https://cloud.githubusercontent.com/assets/16381903/12614870/6d328b28-c528-11e5-8726-86ab03661db0.png)

**Comment by PratibhaSawargi** [comment]
Fixed the issue : "When we provide invalid data and tab out its focus is moved to next successive textfield once we click Ok button on the alert window"
Please verify and let me know if it is not working.

**Comment by rajeshnath3899** [comment]
instead of clearing the invalid data can you highlight it so that if user had typed a long string if you clear off the text field  he has to put his effort to type it again and this can be annoying at times

**Comment by PratibhaSawargi** [comment]
I will work on it.

**Comment by PratibhaSawargi** [comment]
Fixed the issue(38) .
1) Invalid data is highlighting now.Previously we were clearing.
2) If we give name and requisition fields alphanumerics,it is giving alert.

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
