### ISSUE TITLE
Alert message is improper when we switch from technical round to Manager round on candidate rejection

### ISSUE THREAD

**Issue by rajeshnath3899** [vipin1006/eHire#50]
Steps to reproduce

1) Give a technical round feed back 
2) under recommendation select reject
3)Now select managerial section  
4) Alert is shown as "Please complete the technical round before proceeding to managerial round"

Expected output :
This candidate has been 'Rejected' in the Technical Round. Hence you cannot proceed to this round.

**Comment by Tharani-p** [comment]
fixed..please verify

**Comment by rajeshnath3899** [comment]
issue still exists reject a candidate and click on HR section still gives an alert saying "Please complete Technical Round(s) before proceeding to the HR Round"

**Comment by Ajayiosdeveloper** [comment]
Fixed.please verify.

**Comment by rajeshnath3899** [comment]
this issue is fixed and verified hence closing this issue
